project_id = "vqwfnlqmmfesifvdfeju"

[functions.subscriptions]
verify_jwt = true

[functions.upcoming-renewals]
verify_jwt = true

[functions.settings]
verify_jwt = true

[functions.reminders]
verify_jwt = true

[functions.daily-reminder-job]
verify_jwt = false